#------------------------------------------------------------------------------ # Makefile
#
# For building L4-7 cfmask.
#------------------------------------------------------------------------------

all:

install:
	install -d $(PREFIX)/static_data
	install -m 644 EarthSunDistance.txt $(PREFIX)/static_data

clean:

