#------------------------------------------------------------------------------
# Makefile.static
#
# Simple makefile for installing the scripts.
#------------------------------------------------------------------------------

# Target for the executable
all:

install:
	install -d $(PREFIX)/bin
	install -m 755 run_fillminima.py $(PREFIX)/bin
	install -m 664 fillminima.py $(PREFIX)/bin

clean:

